apiVersion: v1
kind: Pod
metadata:
  name: kafka-client
spec:
  containers:
  - name: kafka-client
    image: python:3.12  # hoặc image phù hợp với code của bạn
    command: ['sleep', 'infinity']  # giữ pod running
