apiVersion: batch/v1
kind: Job
metadata:
  name: spark-reddit-streaming
spec:
  template:
    spec:
      containers:
      - name: spark-submit
        image: docker.io/bitnami/spark
        command:
        - /bin/bash
        - -c
        - |
          pip install nltk
          python -c "import nltk; nltk.download('vader_lexicon')"
          spark-submit \
            --master spark://spark-master-svc:7077 \
            --packages org.apache.spark:spark-sql-kafka-0-10_2.12:3.5.1,com.datastax.spark:spark-cassandra-connector_2.12:3.5.1 \
            --conf spark.cassandra.auth.username=cassandra \
            --conf "spark.cassandra.auth.password=$CASSANDRA_PASSWORD" \
            /opt/spark_streaming.py
        volumeMounts:
        - name: script
          mountPath: /opt/spark_streaming.py
          subPath: spark_streaming.py
        env:
        - name: CASSANDRA_PASSWORD
          valueFrom:
            secretKeyRef:
              name: cassandra
              key: cassandra-password
      restartPolicy: Never
      volumes:
      - name: script
        configMap:
          name: spark-streaming
