apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cassandra-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 256Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cassandra
  labels:
    app: cassandra
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cassandra
  template:
    metadata:
      labels:
        app: cassandra
    spec:
      containers:
      - name: cassandra
        image: bitnami/cassandra
        ports:
        - containerPort: 7000
          name: intra-node
        - containerPort: 7001
          name: tls-intra-node
        - containerPort: 7199
          name: jmx
        - containerPort: 9042
          name: cql
        env:
        - name: CASSANDRA_CLUSTER_NAME
          value: "cassandra-cluster"
        - name: CASSANDRA_SEEDS
          value: "cassandra"  # Changed from cassandra-0.cassandra...
        - name: CASSANDRA_HOST
          value: "cassandra"  # Added this
        - name: MAX_HEAP_SIZE
          value: "512M"
        - name: HEAP_NEWSIZE
          value: "100M"
        - name: ALLOW_EMPTY_PASSWORD
          value: "yes"
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "1"
        volumeMounts:
        - name: cassandra-data
          mountPath: /bitnami/cassandra
      volumes:
      - name: cassandra-data
        persistentVolumeClaim:
          claimName: cassandra-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: cassandra
  labels:
    app: cassandra
spec:
  type: ClusterIP
  ports:
  - port: 9042
    targetPort: 9042
    name: cql
  - port: 7000
    targetPort: 7000
    name: intra-node
  - port: 7001
    targetPort: 7001
    name: tls-intra-node
  - port: 7199
    targetPort: 7199
    name: jmx
  selector:
    app: cassandra
